### ISSUE TITLE
JavaMelody dashboard throws a lot of 404's in the browser when using the actuator

### ISSUE THREAD

**Issue by alan-czajkowski** [javamelody/javamelody#1005]
Spring Boot app using dependency:
```xml
    <dependency>
      <groupId>net.bull.javamelody</groupId>
      <artifactId>javamelody-spring-boot-starter</artifactId>
      <version>1.87.0</version>
    </dependency>
```

activate the actuator:
`application.yaml`:
```yaml
...
management:
  endpoints:
    web:
      exposure:
        include: "monitoring"
...
javamelody:
  enabled: true
  spring-monitoring-enabled: true
  management-endpoint-monitoring-enabled: true
  init-parameters:
    url-exclude-pattern: "(/static/.*|/.*\\.css|/.*\\.js|/.*\\.png|/.*\\.jpg|/.*\\.svg)"
...
```

run Spring Boot app locally, dashboard seems to come up fine, but view debug console in browser and you see this:
<img width="1274" alt="Screen Shot 2021-04-13 at 4 12 23 PM" src="https://user-images.githubusercontent.com/3029228/114615343-92067180-9c73-11eb-9f61-c34d9209b00b.png">
