### ISSUE TITLE
JavaMelodyDisabledAutoConfiguration turns off MonitoringFilter in every webapp (if many are deployed)

### ISSUE THREAD

**Issue by ol-loginov** [javamelody/javamelody#1207]
Not a issue actually, more like FYI.
First of all - thanks for javamelody.

Now back to the case. It's a servlet container (actually, Tomcat). With many wars inside.
Every one of those has javamelody-core and javamelody-spring-boot-starter. And in default setup you cannot turn on javamelody only in single servlet context - "all or none" situation.

Workaround we use 
1) exclude `JavaMelodyDisabledAutoConfiguration` with `org.springframework.boot.autoconfigure.AutoConfigurationImportFilter`
2) add the following lines in `WEB-INF/classes/application.yaml` to every war:
```
javamelody:
  enabled: false
  init-parameters:
    disabled: true
```
3) and add standalone configuration file `application.yaml` to every servlet context needed with following:
```
javamelody:
  enabled: true
  init-parameters:
    disabled: false
```

It adds another side effects through, but at least you may visit monitoring url on sites needed.
