### ISSUE TITLE
Being able to set working directory as storage-directory

### ISSUE THREAD

**Issue by gsartori** [javamelody/javamelody#1228]
We need to keep all the application resources within the working directory (well, a folder under the working directory).

Would it be possible, in `application.yml` configuration, to add "./" or something else to specify that the root directory of `storage-directory` is the working dir?

Something like:
```
javamelody:
  init-parameters:
    log: true
    storage-directory: ./my-app-name/monitoring

```

**Comment by evernat** [comment]
In application.yml, you can use `${user.dir}` which is the working dir like this
```
javamelody:
  init-parameters:
    log: true
    storage-directory: ${user.dir}/my-app-name/monitoring
```

You can possibly use one application.yml file per spring profile, to have a default parameter value in application.yml and override it when using a spring profile.
Or you can possibly use a system property like `-Djavamelody.storage-directory=...` in command line to override this parameter.
