### ISSUE TITLE
spring boot (because it is a JDK dynamic proxy that implements)

### ISSUE THREAD

**Issue by An0nymous0** [javamelody/javamelody#666]
1.gradle
```gradle
compile group: 'net.bull.javamelody', name: 'javamelody-spring-boot-starter', version: '1.69.0'
```

2.
```yml
application.yml
   aop:
       auto: true
       proxy-target-class: true
```

3.
```java
@Transactional 
xx method()
```
4.start spring boot
The bean 'xxxService' could not be injected as a 'com.xxx.service.xxxService' because it is a JDK dynamic proxy that implements:

Action:

Consider injecting the bean as one of its interfaces or forcing the use of CGLib-based proxies by setting proxyTargetClass=true on @EnableAsync and/or @EnableCaching.
